### ISSUE TITLE
Update Dependencies & Add Demo Please :)

### ISSUE THREAD

**Issue by tomtom215** [safetychanger/sc-upload#1]
Awesome job on this element!

I was wondering if you could update the dependencies and add docs/demo so I can navigate your code a little better.

I was hoping to your element instead of Vaadin upload since you are using BlueImp already and was hoping to achieve a client side image preview on file selection before uploading the file to the server.

**Comment by rubenstolk** [comment]
Hi @tomtom215, unfortunately I stopped using this element myself in favor of a little bit more specific implementation.

The reason is that I needed to support offline and a more complicated media handling. If you're interested I can still share code though.

**Comment by tomtom215** [comment]
@rubenstolk That would be awesome!

I've gone a different route myself but would love to see what you came up with!

**Comment by rubenstolk** [comment]
Hi @tomtom215 have a look here. As said, it's specific to our media server but it has a couple of useful features. https://gist.github.com/rubenstolk/1ab38f6287e260adb8b84ee158b188ed

Still thinking of making it generic at somepoint...
